# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(-40, -10, 1121, 661))
        self.Background.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Background.setObjectName("Background")
        self.Background_border = QtWidgets.QLabel(self.centralwidget)
        self.Background_border.setGeometry(QtCore.QRect(0, 0, 901, 531))
        self.Background_border.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;")
        self.Background_border.setObjectName("Background_border")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 490, 121, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"font: 20pt \"Nirmala UI\";\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 490, 121, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border:1px solid white;\n"
"font: 20pt \"Nirmala UI\";\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.GUI = QtWidgets.QLabel(self.centralwidget)
        self.GUI.setGeometry(QtCore.QRect(0, 0, 441, 321))
        self.GUI.setStyleSheet("border: 1px solid white;")
        self.GUI.setText("")
        self.GUI.setPixmap(QtGui.QPixmap("GUI Material/B.G/Iron_Template_1.gif"))
        self.GUI.setScaledContents(True)
        self.GUI.setObjectName("GUI")
        self.Gui_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gui_1.setGeometry(QtCore.QRect(440, 0, 451, 211))
        self.Gui_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 1px solid white;")
        self.Gui_1.setText("")
        self.Gui_1.setPixmap(QtGui.QPixmap("GUI Material/VoiceReg/jarvis_jj.gif"))
        self.Gui_1.setScaledContents(True)
        self.Gui_1.setObjectName("Gui_1")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(640, 440, 241, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid white;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.textBrowser.setObjectName("textBrowser")
        self.Terminal = QtWidgets.QLabel(self.centralwidget)
        self.Terminal.setGeometry(QtCore.QRect(0, 320, 621, 211))
        self.Terminal.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid white;")
        self.Terminal.setObjectName("Terminal")
        self.Gui_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gui_2.setGeometry(QtCore.QRect(440, 210, 451, 111))
        self.Gui_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 1px solid white;")
        self.Gui_2.setText("")
        self.Gui_2.setPixmap(QtGui.QPixmap("GUI Material/ExtraGui/initial.gif"))
        self.Gui_2.setScaledContents(True)
        self.Gui_2.setObjectName("Gui_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Background.setText(_translate("MainWindow", "TextLabel"))
        self.Background_border.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "CLOSE"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time:</p></body></html>"))
        self.Terminal.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
